// This file is auto-generated by @hey-api/openapi-ts

export type App = {
    clientId?: string;
    description?: string;
    iconUrl?: string;
    organizationId?: number;
    ping?: number;
    slug?: string;
    title?: string;
    type?: 'OPENID' | 'SAML' | 'SMARTLINK';
    url?: string;
};

export type type = 'OPENID' | 'SAML' | 'SMARTLINK';

export type Folder = {
    forAllUsers?: boolean;
    id?: number;
    name?: string;
    organizationId?: number;
    parentId?: number;
    path?: string;
};

/**
 * Matches any valid JSON value
 */
export type JsonValue = unknown;

export type LogEvent = {
    appClientId?: string;
    createdAt?: string;
    /**
     * From https://github.com/sindresorhus/type-fest/
     * Matches any valid JSON value.
     */
    data?: JsonValue;
    deviceId?: number;
    folderId?: number;
    id?: number;
    membershipId?: number;
    message?: string;
    organizationId?: number;
    shadowItAppId?: number;
    type?: number;
};

export type Membership = {
    createdAt?: string;
    email?: string;
    firstName?: string;
    id?: number;
    language?: string;
    name?: string;
    organizationId?: number;
    phone?: string;
    registerLink?: string;
    role?: 'ADMIN' | 'OWNER' | 'USER';
    status?: 'ACTIVE' | 'INACTIVE';
    updatedAt?: string;
};

export type role = 'ADMIN' | 'OWNER' | 'USER';

export type status = 'ACTIVE' | 'INACTIVE';

export type Message = {
    createdAt?: string;
    creatorId?: number;
    description?: string;
    expiration?: string;
    id?: number;
    organizationId?: number;
    recipientId?: number;
    status?: string;
    title?: string;
    type?: string;
};

export type Organization = {
    id?: number;
    name?: string;
    maxUser?: number;
    maxApp?: number;
    maxDomain?: number;
    maxFolder?: number;
    createdAt?: string;
    updatedAt?: string;
    admin?: boolean;
    allowCreation?: boolean;
    createOnly?: boolean;
    licenseExpiration?: string;
    stripeCustomerId?: string;
    language?: string;
    license?: 'FREE' | 'PRO' | 'ENTERPRISE';
    visibility?: 'PUBLIC' | 'PRIVATE';
    rateLimit?: {
        id?: number;
        organizationId?: number;
        limit?: number;
        window?: number;
        createdAt?: string;
        updatedAt?: string;
    };
    _count?: {
        Memberships?: number;
        Apps?: number;
        Folders?: number;
        Domains?: number;
        LogEvents?: number;
        Payments?: number;
        Message?: number;
        Device?: number;
        ShadowITApp?: number;
        DeviceAuthRules?: number;
    };
};

export type license = 'FREE' | 'PRO' | 'ENTERPRISE';

export type visibility = 'PUBLIC' | 'PRIVATE';

export type GetAppByClientIdData = {
    path: {
        clientId: unknown;
    };
};

export type GetAppByClientIdResponse = (App);

export type GetAppByClientIdError = (unknown);

export type PutAppByClientIdData = {
    body: {
        title?: string;
        url?: string;
        iconUrl?: string;
        slug?: string;
        description?: string;
    };
    path: {
        /**
         * The client ID of the app
         */
        clientId: string;
    };
};

export type PutAppByClientIdResponse = (App);

export type PutAppByClientIdError = (unknown);

export type DeleteAppByClientIdData = {
    path: {
        clientId: unknown;
    };
};

export type DeleteAppByClientIdResponse = (App);

export type DeleteAppByClientIdError = (unknown);

export type PostAppData = {
    body: {
        /**
         * The title of the app
         */
        title: string;
        /**
         * The URL of the app
         */
        url?: string;
        /**
         * The icon URL of the app
         */
        iconUrl?: string;
        /**
         * Optional slug for the app
         */
        slug?: string;
        /**
         * The description of the app
         */
        description?: string;
    };
};

export type PostAppResponse = (App);

export type PostAppError = (unknown);

export type GetAppsData = {
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of items per page
         */
        pageSize?: number;
        /**
         * Comma-separated list of provisioning types (none, scim)
         */
        provisioningFilter?: string;
        /**
         * Search text (searches in title, url, slug)
         */
        search?: string;
        /**
         * Field to sort by
         */
        sortBy?: 'title' | 'type' | 'provisioning';
        /**
         * Sort order
         */
        sortOrder?: 'asc' | 'desc';
        /**
         * Comma-separated list of app types to filter
         */
        typeFilter?: string;
    };
};

export type GetAppsResponse = ({
    apps?: Array<App>;
    /**
     * Total number of apps
     */
    total?: number;
});

export type GetAppsError = (unknown);

export type PostAppsData = {
    body: {
        apps?: Array<{
            /**
             * The title of the app
             */
            title?: string;
            /**
             * The URL of the app
             */
            url?: string;
            /**
             * The icon URL of the app
             */
            iconUrl?: string;
            /**
             * Optional slug for the app
             */
            slug?: string;
            /**
             * The description of the app
             */
            description?: string;
        }>;
    };
};

export type PostAppsResponse = (Array<App>);

export type PostAppsError = (unknown);

export type GetEventsData = {
    query?: {
        /**
         * Filter by app client ID
         */
        appClientId?: string;
        /**
         * Filter by device ID
         */
        deviceId?: number;
        /**
         * Filter by folder ID
         */
        folderId?: number;
        /**
         * Start date for filtering events (timestamp in seconds)
         */
        fromDate?: number;
        /**
         * Filter by membership ID
         */
        membershipId?: number;
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of events per page (maximum 50)
         */
        pageSize?: number;
        /**
         * Filter by shadow app ID
         */
        shadowAppId?: number;
        /**
         * Field to sort by
         */
        sortBy?: 'date' | 'message' | 'membership' | 'type';
        /**
         * Sort order (ascending or descending)
         */
        sortOrder?: 'asc' | 'desc';
        /**
         * End date for filtering events (timestamp in seconds)
         */
        toDate?: number;
        /**
         * Type of log event (APP_OPEN = 0, SMARTLINK_CONNECT = 1, SMARTLINK_CONNECT_FAIL = 2, SMARTLINK_CONNECT_DENIED = 3, SMARTLINK_EXTENSION_CONNECT = 4, SMARTLINK_EXTENSION_CONNECT_FAIL = 5, SMARTLINK_EXTENSION_CONNECT_DENIED = 6, POST_PASSWORD = 7, FORM_BLOCKED = 8)
         */
        type?: number;
    };
};

export type GetEventsResponse = ({
    events?: Array<LogEvent>;
    /**
     * Total number of events matching the filters
     */
    total?: number;
});

export type GetEventsError = (unknown);

export type GetFolderByIdAppsData = {
    path: {
        /**
         * Folder ID
         */
        id: number;
    };
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of items per page
         */
        pageSize?: number;
        /**
         * Comma-separated list of provisioning types (none, scim)
         */
        provisioningFilter?: string;
        /**
         * Search text (searches in title, url, slug)
         */
        search?: string;
        /**
         * Field to sort by
         */
        sortBy?: 'title' | 'type' | 'provisioning';
        /**
         * Sort order
         */
        sortOrder?: 'asc' | 'desc';
        /**
         * Comma-separated list of app types to filter
         */
        typeFilter?: string;
    };
};

export type GetFolderByIdAppsResponse = ({
    apps?: Array<App>;
    /**
     * Total number of apps
     */
    total?: number;
});

export type GetFolderByIdAppsError = (unknown);

export type GetFolderByIdMembershipsData = {
    path: {
        /**
         * Folder ID
         */
        id: number;
    };
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of items per page
         */
        pageSize?: number;
        /**
         * Comma-separated list of roles to filter
         */
        roleFilter?: string;
        /**
         * Search text (searches in firstName, name, email)
         */
        search?: string;
        /**
         * Field to sort by
         */
        sortBy?: 'firstName' | 'name' | 'email' | 'role' | 'status';
        /**
         * Sort order
         */
        sortOrder?: 'asc' | 'desc';
        /**
         * Comma-separated list of states (registered, unregistered)
         */
        stateFilter?: string;
        /**
         * Comma-separated list of statuses to filter
         */
        statusFilter?: string;
    };
};

export type GetFolderByIdMembershipsResponse = ({
    memberships?: Array<Membership>;
    /**
     * Total number of memberships
     */
    total?: number;
});

export type GetFolderByIdMembershipsError = (unknown);

export type GetFolderByIdData = {
    path: {
        id: unknown;
    };
};

export type GetFolderByIdResponse = (Folder);

export type GetFolderByIdError = (unknown);

export type DeleteFolderByIdData = {
    path: {
        /**
         * The ID of the folder to delete
         */
        id: number;
    };
};

export type DeleteFolderByIdResponse = (Folder);

export type DeleteFolderByIdError = (unknown);

export type PostFolderData = {
    body: {
        name?: string;
        /**
         * ID of the parent folder
         */
        parentId?: number;
    };
};

export type PostFolderResponse = (Folder);

export type PostFolderError = (unknown);

export type GetFoldersResponse = (Array<Folder>);

export type GetFoldersError = (unknown);

export type PostImportAppsData = {
    body: {
        apps?: Array<{
            /**
             * The title of the app
             */
            title?: string;
            /**
             * The URL of the app
             */
            url?: string;
            /**
             * The icon URL of the app
             */
            iconUrl?: string;
            /**
             * Optional slug for the app
             */
            slug?: string;
            /**
             * The description of the app
             */
            description?: string;
            /**
             * The type of the app
             */
            type?: 'SMARTLINK' | 'OIDC' | 'SAML';
            /**
             * Folder paths for the app
             */
            folders?: Array<(string)>;
            /**
             * Custom login URL for the app
             */
            loginUrl?: string;
        }>;
    };
};

export type PostImportAppsResponse = ({
    /**
     * Number of apps imported
     */
    count?: number;
});

export type PostImportAppsError = (unknown);

export type PostImportMembershipsData = {
    body: {
        users?: Array<{
            /**
             * Last name of the user
             */
            name?: string;
            /**
             * First name of the user
             */
            firstName?: string;
            /**
             * Email address of the user
             */
            email?: string;
            /**
             * Phone number of the user
             */
            phone?: string;
            /**
             * Whether the user should have admin role
             */
            admin?: boolean;
            /**
             * Folder paths for the user
             */
            folders?: Array<(string)>;
        }>;
    };
};

export type PostImportMembershipsResponse = ({
    /**
     * Number of memberships imported
     */
    count?: number;
});

export type PostImportMembershipsError = (unknown);

export type PostMembershipByIdDeactivateData = {
    path: {
        /**
         * The ID of the membership to deactivate
         */
        id: string;
    };
};

export type PostMembershipByIdDeactivateResponse = (Membership);

export type PostMembershipByIdDeactivateError = (unknown);

export type PostMembershipByIdRegisterData = {
    body: {
        /**
         * Send an invitation email to the user
         */
        sendMail?: boolean;
    };
    path: {
        /**
         * The membership ID
         */
        id: number;
    };
};

export type PostMembershipByIdRegisterResponse = ({
    /**
     * The registration link for the user
     */
    registerLink?: string;
    /**
     * Whether an email was sent
     */
    mailSent?: boolean;
});

export type PostMembershipByIdRegisterError = (unknown);

export type GetMembershipByIdData = {
    path: {
        id: unknown;
    };
};

export type GetMembershipByIdResponse = (Membership);

export type GetMembershipByIdError = (unknown);

export type PutMembershipByIdData = {
    body: {
        name?: string;
        firstName?: string;
        phone?: string;
        email?: string;
        role?: string;
        language?: string;
        status?: string;
    };
    path: {
        id: unknown;
    };
};

export type PutMembershipByIdResponse = (Membership);

export type PutMembershipByIdError = (unknown);

export type DeleteMembershipByIdData = {
    path: {
        /**
         * The ID of the membership to delete
         */
        id: number;
    };
};

export type DeleteMembershipByIdResponse = (Membership);

export type DeleteMembershipByIdError = (unknown);

export type PostMembershipData = {
    body: {
        name?: string;
        firstName?: string;
        phone?: string;
        email?: string;
        /**
         * Set the membership as admin
         */
        isAdmin?: boolean;
    };
};

export type PostMembershipResponse = (Membership);

export type PostMembershipError = (unknown);

export type GetMembershipsResponse = (Array<Membership>);

export type GetMembershipsError = (unknown);

export type PostMembershipsData = {
    body: {
        memberships?: Array<{
            name?: string;
            firstName?: string;
            phone?: string;
            email?: string;
            /**
             * Set the membership as admin
             */
            isAdmin?: boolean;
        }>;
    };
};

export type PostMembershipsResponse = (Array<Membership>);

export type PostMembershipsError = (unknown);

export type GetMembershipsSearchData = {
    query: {
        /**
         * Page number for pagination
         */
        page: number;
        /**
         * Number of items per page (default is 10)
         */
        pageSize?: number;
        /**
         * Comma-separated list of roles to filter by (roles are OWNER, ADMIN, USER)
         */
        roles?: string;
        /**
         * Search term in name, first name, email, or phone
         */
        search?: string;
        /**
         * Filter by registration status
         */
        statusFilter?: 'all' | 'registered' | 'unregistered';
    };
};

export type GetMembershipsSearchResponse = ({
    memberships?: Array<Membership>;
    /**
     * Total number of memberships
     */
    count?: number;
});

export type GetMembershipsSearchError = (unknown);

export type GetOrganizationResponse = (Organization);

export type GetOrganizationError = (unknown);